apiName: "Peters API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../workshop-client/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.postgresql.Driver
  url: "jdbc:postgresql://localhost/ipsen3/"
  user: admin
  password: password
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: none