apiName: "Peters API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../workshop-client/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/ipsen3?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
  user: root
  password: spiegel
  properties:
      hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: validate